"""
389. Find the Difference
Easy
4.8K
465
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
"""
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        hs = {}
        for x in s:
            if x in hs:
                hs[x]+=1
            else:
                hs[x]=1
        for x in t:
            if x in hs:
                if hs[x] == 1:
                    del hs[x]
                else:
                    hs[x] -=1
            else:
                return x
        return -1
